apiVersion: v1
kind: Namespace
metadata: 
  name: csharp
  labels: 
    name: tai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: csharp
  labels:
    control-plane: operator
    app.kubernetes.io/version: "0.0.1"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator
  labels:
    control-plane: operator
    app.kubernetes.io/version: "0.0.1"
rules:
  - apiGroups:
      - "authorization.k8s.io"
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      -