apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20


# ports:
# - name: liveness-port
#   containerPort: 8080
#   hostPort: 8080

# livenessProbe:
#   httpGet:
#     path: /healthz
#     port: liveness-port
#   failureThreshold: 1
#   periodSeconds: 10

# startupProbe:
#   httpGet:
#     path: /healthz
#     port: liveness-port
#   failureThreshold: 30
#   periodSeconds: 10      
#HTTP or TCP check, with a failureThreshold * periodSeconds